database:
  dsn: "root:password@tcp(127.0.0.1:3306)/chatroom?charset=utf8mb4&parseTime=True&loc=Local"

jwt:
  secret: "your-secret-key"
  expiration: 24h  # 支持时间单位：h(小时)、m(分钟)、s(秒)

websocket:
  message_retry_count: 3 # 重试次数
  message_retry_interval_ms: 50 # 重试间隔（毫秒）