log:
  level: "debug" # debug, info, warn, error, fatal, panic
  production_mode: false

database:
  dsn: "root:password@tcp(127.0.0.1:3306)/chatroom?charset=utf8mb4&parseTime=True&loc=Local"

jwt:
  secret: "your-secret-key"
  expiration: 24h  # 支持时间单位：h(小时)、m(分钟)、s(秒)

websocket:
  broadcast_buffer_size: 256
  message_retry_count: 3 # 重试次数
  message_retry_interval_ms: 100 # 重试间隔（毫秒）

server:                 # Add this section
  address: ":8080"      # Address and port to listen on
  gin_mode: "debug"     # Gin mode: debug, release, test

file:
  storage_path: "uploads"  # 文件存储目录
  max_file_size: 52428800  # 50MB (50 * 1024 * 1024 字节)